version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INTERNAL
      KAFKA_LISTENER_PORT_INTERNAL: 9093
      KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL
      KAFKA_LISTENER_PORT_EXTERNAL: 9092
      KAFKA_LISTENER_INTER_BROKER_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_INTERNAL: INTERNAL
      KAFKA_LISTENER_PORT: 9092
    ports:
      - "9092:9092"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: polling_user
      POSTGRES_PASSWORD: Ravijha
      POSTGRES_DB: polling_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
